package com.moomanow.web.security.openid.bean;




import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.moomanow.core.common.bean.EntityBean;

/**
 * ClientDetail generated by hbm2java
 */
@Entity
@Table(name="SYS_T_CLIENT_DETAIL")
public class ClientDetail  implements EntityBean,java.io.Serializable {


     private Integer idClientDetail;
     private String issuer;
     private String clientId;
     private String clientSecret;
     private String scope;
     private String redirectUris; 
     private String status;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public ClientDetail() {
    }

    public ClientDetail(String issuer, String clientId, String clientSecret, String scope, String redirectUris, String status, Date createDate, String createUser, Date updateDate, String updateUser) {
       this.issuer = issuer;
       this.clientId = clientId;
       this.clientSecret = clientSecret;
       this.scope = scope;
       this.redirectUris = redirectUris;
       this.status = status;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_CLIENT_DETAIL", unique=true, nullable=false)
    public Integer getIdClientDetail() {
        return this.idClientDetail;
    }
    
    public void setIdClientDetail(Integer idClientDetail) {
        this.idClientDetail = idClientDetail;
    }

    
    @Column(name="ISSUER", length=254)
    public String getIssuer() {
        return this.issuer;
    }
    
    public void setIssuer(String issuer) {
        this.issuer = issuer;
    }

    
    @Column(name="CLIENT_ID", length=254)
    public String getClientId() {
        return this.clientId;
    }
    
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    
    @Column(name="CLIENT_SECRET", length=254)
    public String getClientSecret() {
        return this.clientSecret;
    }
    
    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret;
    }

    
    @Column(name="SCOPE", length=254)
    public String getScope() {
        return this.scope;
    }
    
    public void setScope(String scope) {
        this.scope = scope;
    }

    
    @Column(name="REDIRECT_URIS", length=65535)
    public String getRedirectUris() {
        return this.redirectUris;
    }
    
    public void setRedirectUris(String redirectUris) {
        this.redirectUris = redirectUris;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="CREATE_DATE", length=0)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    
    @Column(name="UPDATE_DATE", length=0)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER")
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("idClientDetail").append("='").append(getIdClientDetail()).append("' ");			
      buffer.append("issuer").append("='").append(getIssuer()).append("' ");			
      buffer.append("clientId").append("='").append(getClientId()).append("' ");			
      buffer.append("clientSecret").append("='").append(getClientSecret()).append("' ");			
      buffer.append("scope").append("='").append(getScope()).append("' ");			
      buffer.append("redirectUris").append("='").append(getRedirectUris()).append("' ");			
      buffer.append("status").append("='").append(getStatus()).append("' ");			
      buffer.append("createDate").append("='").append(getCreateDate()).append("' ");			
      buffer.append("createUser").append("='").append(getCreateUser()).append("' ");			
      buffer.append("updateDate").append("='").append(getUpdateDate()).append("' ");			
      buffer.append("updateUser").append("='").append(getUpdateUser()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClientDetail) ) return false;
		 ClientDetail castOther = ( ClientDetail ) other; 
         
		 return ( (this.getIdClientDetail()==castOther.getIdClientDetail()) || ( this.getIdClientDetail()!=null && castOther.getIdClientDetail()!=null && this.getIdClientDetail().equals(castOther.getIdClientDetail()) ) )
 && ( (this.getIssuer()==castOther.getIssuer()) || ( this.getIssuer()!=null && castOther.getIssuer()!=null && this.getIssuer().equals(castOther.getIssuer()) ) )
 && ( (this.getClientId()==castOther.getClientId()) || ( this.getClientId()!=null && castOther.getClientId()!=null && this.getClientId().equals(castOther.getClientId()) ) )
 && ( (this.getClientSecret()==castOther.getClientSecret()) || ( this.getClientSecret()!=null && castOther.getClientSecret()!=null && this.getClientSecret().equals(castOther.getClientSecret()) ) )
 && ( (this.getScope()==castOther.getScope()) || ( this.getScope()!=null && castOther.getScope()!=null && this.getScope().equals(castOther.getScope()) ) )
 && ( (this.getRedirectUris()==castOther.getRedirectUris()) || ( this.getRedirectUris()!=null && castOther.getRedirectUris()!=null && this.getRedirectUris().equals(castOther.getRedirectUris()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getCreateDate()==castOther.getCreateDate()) || ( this.getCreateDate()!=null && castOther.getCreateDate()!=null && this.getCreateDate().equals(castOther.getCreateDate()) ) )
 && ( (this.getCreateUser()==castOther.getCreateUser()) || ( this.getCreateUser()!=null && castOther.getCreateUser()!=null && this.getCreateUser().equals(castOther.getCreateUser()) ) )
 && ( (this.getUpdateDate()==castOther.getUpdateDate()) || ( this.getUpdateDate()!=null && castOther.getUpdateDate()!=null && this.getUpdateDate().equals(castOther.getUpdateDate()) ) )
 && ( (this.getUpdateUser()==castOther.getUpdateUser()) || ( this.getUpdateUser()!=null && castOther.getUpdateUser()!=null && this.getUpdateUser().equals(castOther.getUpdateUser()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdClientDetail() == null ? 0 : this.getIdClientDetail().hashCode() );
         result = 37 * result + ( getIssuer() == null ? 0 : this.getIssuer().hashCode() );
         result = 37 * result + ( getClientId() == null ? 0 : this.getClientId().hashCode() );
         result = 37 * result + ( getClientSecret() == null ? 0 : this.getClientSecret().hashCode() );
         result = 37 * result + ( getScope() == null ? 0 : this.getScope().hashCode() );
         result = 37 * result + ( getRedirectUris() == null ? 0 : this.getRedirectUris().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getCreateDate() == null ? 0 : this.getCreateDate().hashCode() );
         result = 37 * result + ( getCreateUser() == null ? 0 : this.getCreateUser().hashCode() );
         result = 37 * result + ( getUpdateDate() == null ? 0 : this.getUpdateDate().hashCode() );
         result = 37 * result + ( getUpdateUser() == null ? 0 : this.getUpdateUser().hashCode() );
         return result;
   }   


}


