package com.moomanow.core.common.dao;



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VaPdMilitaryStatus generated by hbm2java
 */
@Entity
@Table(name="JOB_C_VA_PD_MILITARY_STATUS"
)
public class VaPdMilitaryStatus  implements com.moomanow.core.common.bean.EntityBean,java.io.Serializable {


     private Long idVaPdMilitaryStatus;
     private MilitaryStatus militaryStatus;
     private Vacancy vacancy;
     private String status;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public VaPdMilitaryStatus() {
    }

	
    public VaPdMilitaryStatus(MilitaryStatus militaryStatus) {
        this.militaryStatus = militaryStatus;
    }
    public VaPdMilitaryStatus(MilitaryStatus militaryStatus, Vacancy vacancy, String status, Date createDate, String createUser, Date updateDate, String updateUser) {
       this.militaryStatus = militaryStatus;
       this.vacancy = vacancy;
       this.status = status;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_VA_PD_MILITARY_STATUS", unique=true, nullable=false)
    public Long getIdVaPdMilitaryStatus() {
        return this.idVaPdMilitaryStatus;
    }
    
    public void setIdVaPdMilitaryStatus(Long idVaPdMilitaryStatus) {
        this.idVaPdMilitaryStatus = idVaPdMilitaryStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_MILITARY_STATUS", nullable=false)
    public MilitaryStatus getMilitaryStatus() {
        return this.militaryStatus;
    }
    
    public void setMilitaryStatus(MilitaryStatus militaryStatus) {
        this.militaryStatus = militaryStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_VACANCY")
    public Vacancy getVacancy() {
        return this.vacancy;
    }
    
    public void setVacancy(Vacancy vacancy) {
        this.vacancy = vacancy;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="CREATE_DATE", length=0)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    
    @Column(name="UPDATE_DATE", length=0)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER")
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("idVaPdMilitaryStatus").append("='").append(getIdVaPdMilitaryStatus()).append("' ");			
      buffer.append("militaryStatus").append("='").append(getMilitaryStatus()).append("' ");			
      buffer.append("vacancy").append("='").append(getVacancy()).append("' ");			
      buffer.append("status").append("='").append(getStatus()).append("' ");			
      buffer.append("createDate").append("='").append(getCreateDate()).append("' ");			
      buffer.append("createUser").append("='").append(getCreateUser()).append("' ");			
      buffer.append("updateDate").append("='").append(getUpdateDate()).append("' ");			
      buffer.append("updateUser").append("='").append(getUpdateUser()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VaPdMilitaryStatus) ) return false;
		 VaPdMilitaryStatus castOther = ( VaPdMilitaryStatus ) other; 
         
		 return ( (this.getIdVaPdMilitaryStatus()==castOther.getIdVaPdMilitaryStatus()) || ( this.getIdVaPdMilitaryStatus()!=null && castOther.getIdVaPdMilitaryStatus()!=null && this.getIdVaPdMilitaryStatus().equals(castOther.getIdVaPdMilitaryStatus()) ) )
 && ( (this.getMilitaryStatus()==castOther.getMilitaryStatus()) || ( this.getMilitaryStatus()!=null && castOther.getMilitaryStatus()!=null && this.getMilitaryStatus().equals(castOther.getMilitaryStatus()) ) )
 && ( (this.getVacancy()==castOther.getVacancy()) || ( this.getVacancy()!=null && castOther.getVacancy()!=null && this.getVacancy().equals(castOther.getVacancy()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getCreateDate()==castOther.getCreateDate()) || ( this.getCreateDate()!=null && castOther.getCreateDate()!=null && this.getCreateDate().equals(castOther.getCreateDate()) ) )
 && ( (this.getCreateUser()==castOther.getCreateUser()) || ( this.getCreateUser()!=null && castOther.getCreateUser()!=null && this.getCreateUser().equals(castOther.getCreateUser()) ) )
 && ( (this.getUpdateDate()==castOther.getUpdateDate()) || ( this.getUpdateDate()!=null && castOther.getUpdateDate()!=null && this.getUpdateDate().equals(castOther.getUpdateDate()) ) )
 && ( (this.getUpdateUser()==castOther.getUpdateUser()) || ( this.getUpdateUser()!=null && castOther.getUpdateUser()!=null && this.getUpdateUser().equals(castOther.getUpdateUser()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdVaPdMilitaryStatus() == null ? 0 : this.getIdVaPdMilitaryStatus().hashCode() );
         result = 37 * result + ( getMilitaryStatus() == null ? 0 : this.getMilitaryStatus().hashCode() );
         result = 37 * result + ( getVacancy() == null ? 0 : this.getVacancy().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getCreateDate() == null ? 0 : this.getCreateDate().hashCode() );
         result = 37 * result + ( getCreateUser() == null ? 0 : this.getCreateUser().hashCode() );
         result = 37 * result + ( getUpdateDate() == null ? 0 : this.getUpdateDate().hashCode() );
         result = 37 * result + ( getUpdateUser() == null ? 0 : this.getUpdateUser().hashCode() );
         return result;
   }   


}


