package com.moomanow.core.common.dao;



import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vacancy generated by hbm2java
 */
@Entity
@Table(name="JOB_C_VACANCY"
)
public class Vacancy  implements com.moomanow.core.common.bean.EntityBean,java.io.Serializable {


     private Long idVacancy;
     private Long idUser;
     private Integer noPosition;
     private Date dateStart;
     private Date dateExpire;
     private String status;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;
     private List<VaPdMilitaryStatus> vaPdMilitaryStatuses = new ArrayList<VaPdMilitaryStatus>(0);

    public Vacancy() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_VACANCY", unique=true, nullable=false)
    public Long getIdVacancy() {
        return this.idVacancy;
    }
    
    public void setIdVacancy(Long idVacancy) {
        this.idVacancy = idVacancy;
    }


    
    @Column(name="ID_USER")
    public Long getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Long idUser) {
        this.idUser = idUser;
    }

    
    @Column(name="NO_POSITION")
    public Integer getNoPosition() {
        return this.noPosition;
    }
    
    public void setNoPosition(Integer noPosition) {
        this.noPosition = noPosition;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_START", length=0)
    public Date getDateStart() {
        return this.dateStart;
    }
    
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_EXPIRE", length=0)
    public Date getDateExpire() {
        return this.dateExpire;
    }
    
    public void setDateExpire(Date dateExpire) {
        this.dateExpire = dateExpire;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="CREATE_DATE", length=0)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    
    @Column(name="UPDATE_DATE", length=0)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER")
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }



@OneToMany(fetch=FetchType.LAZY, mappedBy="vacancy")
    public List<VaPdMilitaryStatus> getVaPdMilitaryStatuses() {
        return this.vaPdMilitaryStatuses;
    }
    
    public void setVaPdMilitaryStatuses(List<VaPdMilitaryStatus> vaPdMilitaryStatuses) {
        this.vaPdMilitaryStatuses = vaPdMilitaryStatuses;
    }



}


